version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db # Created database
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - postgresserver

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
